# Generated by Django 4.0.5 on 2022-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
                ('heure_cellule', models.FloatField(max_length=10)),
                ('landings', models.DecimalField(decimal_places=10, max_digits=10)),
                ('cruise_speed', models.DecimalField(decimal_places=10, max_digits=10)),
                ('libelle', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cellules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cellule', models.CharField(max_length=50)),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(max_length=30)),
                ('objet_doc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mission_Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_mission', models.CharField(max_length=50)),
                ('lieu_depart', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('pax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heure_decollage', models.CharField(max_length=10)),
                ('ETA', models.CharField(max_length=10)),
                ('profit_de', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='moyens_sic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel', models.CharField(max_length=50)),
                ('type_materiel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ops', models.CharField(max_length=20)),
                ('nom_ops', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_pers', models.CharField(max_length=20)),
                ('nom_pers', models.CharField(max_length=30)),
                ('prenom_pers', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=30)),
                ('fonction', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panne', models.CharField(max_length=500)),
                ('disponibilite', models.CharField(max_length=10)),
            ],
        ),
    ]
