# Generated by Django 4.0.5 on 2022-07-08 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OPS', '0002_rename_aeronefs_aeronef_rename_cellules_cellule'),
    ]

    operations = [
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation_auto', models.CharField(max_length=20)),
                ('libelle_auto', models.CharField(max_length=50)),
                ('nombre_place', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_auto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mission_Terre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_mission', models.CharField(max_length=50)),
                ('lieu_depart', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('pax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heure_decollage', models.CharField(max_length=10)),
                ('ETA', models.CharField(max_length=10)),
                ('profit_de', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation_moto', models.CharField(max_length=20)),
                ('libelle_moto', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
        migrations.AddField(
            model_name='documents',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OPS.operations'),
        ),
        migrations.AddField(
            model_name='mission_air',
            name='aeronef',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='OPS.aeronef'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type_doc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
